services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    volumes:
      - ./:/app
      - /app/node_modules